### ISSUE TITLE
Compilation issue on Arch linux

### ISSUE THREAD

**Issue by S3gmentati0nFault** [mbeutel/makeshift#11]
This is an issue that has surely something to do with recent updates to either the `clang` compiler or ` libc++` (I am on a very mutable distribution) and when compiling the `islgen` project I got the following error

```
$ cmake --build build/clang --clean-first
[1/1] Cleaning all built files...
Cleaning... 26 files.
[12/17] Building CXX object src/CMakeFiles/islgen.dir/Debug/trace.cpp.o
FAILED: [code=1] src/CMakeFiles/islgen.dir/Debug/trace.cpp.o 
/usr/bin/clang++ -DCMAKE_INTDIR=\"Debug\" -I/home/marvin/Projects/ASC/Research/islgen/include -I/home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/gsl-lite/e0c10691bbe117f75e4fd7cc970a29d10e6ae5f1/include -I/home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/makeshift/7d2c338fb5e18103f035d4acbe4ebeef1b07b320/include -I/home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/patton/864a6a9438ad0963be2505c7ebec630790b8ccd4/include -stdlib=libc++ -g -std=gnu++23 -Wall -Wextra -pedantic -MD -MT src/CMakeFiles/islgen.dir/Debug/trace.cpp.o -MF src/CMakeFiles/islgen.dir/Debug/trace.cpp.o.d @src/CMakeFiles/islgen.dir/Debug/trace.cpp.o.modmap -o src/CMakeFiles/islgen.dir/Debug/trace.cpp.o -c /home/marvin/Projects/ASC/Research/islgen/src/trace.cpp
In file included from /home/marvin/Projects/ASC/Research/islgen/src/trace.cpp:2:
In file included from /home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/makeshift/7d2c338fb5e18103f035d4acbe4ebeef1b07b320/include/makeshift/iomanip.hpp:15:
In file included from /home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/makeshift/7d2c338fb5e18103f035d4acbe4ebeef1b07b320/include/makeshift/metadata.hpp:18:
In file included from /home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/makeshift/7d2c338fb5e18103f035d4acbe4ebeef1b07b320/include/makeshift/detail/metadata.hpp:20:
In file included from /home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/makeshift/7d2c338fb5e18103f035d4acbe4ebeef1b07b320/include/makeshift/detail/tuple.hpp:15:
/home/marvin/Projects/ASC/Research/islgen/build/clang/CPM-cache/makeshift/7d2c338fb5e18103f035d4acbe4ebeef1b07b320/include/makeshift/detail/constval.hpp:323:5: error: no member named 'copy' in namespace 'std::ranges'; did you mean 'bcopy'?
  323 |     std::ranges::copy(range, result.begin());
      |     ^~~~~~~~~~~~~~~~~
      |     bcopy
/usr/include/strings.h:38:13: note: 'bcopy' declared here
   38 | extern void bcopy (const void *__src, void *__dest, size_t __n)
      |             ^
1 error generated.
[15/17] Building CXX object _deps/patton-build/src/CMakeFiles/patton.dir/Debug/cpuinfo.cpp.o
ninja: build stopped: subcommand failed.
```

I can confirm that the build procedure only affected my Arch linux based machines because when I tried to build the code on Debian it gave no problems, I will try to troubleshoot the issue myself later on and see what is going on.

**Comment by mbeutel** [comment]
Looks like I forgot to include `<algorithm>` where [`std::ranges::copy()`](https://en.cppreference.com/w/cpp/algorithm/ranges/copy) lives. This should be fixed with the latest commit in master.

**Comment by S3gmentati0nFault** [comment]
It's interesting though because even without the header file it does compile on clang 21.1.8, it doesn't even give warnings about that

**Comment by mbeutel** [comment]
This is probably because some other header in the libc++ version shipped with clang 21.1.8 indirectly includes a definition of `std::ranges::copy()`.

You often get away with accidentally not including some standard library headers because the standard library has many internal dependencies. For instance, [`std::reverse_iterator<>`](https://en.cppreference.com/w/cpp/iterator/reverse_iterator.html) is defined in `<iterator>`, but [`std::vector<>::reverse_iterator`](https://en.cppreference.com/w/cpp/container/vector.html), which lives in `<vector>`, has to be of type `std::reverse_iterator<>`; so in practice, you can use a `std::reverse_iterator<>` even if you only included `<vector>` but not `<iterator>`.

By the way, how is Clang 21.1.8 a downgrade from 21.1.1-1? By semantic versioning rules, the former should be the newer release.

**Comment by mbeutel** [comment]
(Feel free to close the issue if you can confirm that my commit resolves the problem.)

**Comment by S3gmentati0nFault** [comment]
With the  `<algorithm>` header the library still compiles without any problems, I'll keep you updated to see if there are still problems with newer releases of clang, for the time being I will remain on 21.1.8

> By the way, how is Clang 21.1.8 a downgrade from 21.1.1-1?

My bad, it was a typo, I downgraded from 22.1.1-1 to 21.1.8
